import os

# App
APP_NAME = "LipaLess"
APP_CONFIG_ENV_VAR = APP_NAME + "_CONFIG"
DEV_CONFIG_VAR = "dev"
PROD_CONFIG_VAR = "prod"
TESTING_CONFIG_VAR = "testing"

# Database
DATABASE_URL_ENV_NAME = APP_NAME + "_DATABASE_URL"
DATABASE_URL = os.getenv(DATABASE_URL_ENV_NAME)

TESTING_DATABASE_URL_ENV_NAME = APP_NAME + "_TESTING_DATABASE_URL"
TESTING_DATABASE_URL = os.getenv(TESTING_DATABASE_URL_ENV_NAME)

# Session management
REDIS_URL_ENV_VAR = "REDISCLOUD_URL"
LOCAL_REDIS_URL = "127.0.0.1:6379"

# Roles
ROLES_YAML_ENV_VAR = APP_NAME + "_ROLES"
OWNER_ROLE_NAME = "owner"
ADMIN_ROLE_NAME = "admin"
CASHIER_ROLE_NAME = "cashier"

# Billing business
MINIMUM_PAYMENT_ID = 100000
MAXIMUM_PAYMENT_ID = 900000

BILLING_SCH = None
BILLING_INTERVAL_IN_SECONDS = 60
BILLING_AMOUNT_PER_INTERVAL_IN_SHILLINGS = 10
