import os

# App
APP_NAME = "LipaLess"
APP_CONFIG_ENV_VAR = APP_NAME + "_CONFIG"
DEV_CONFIG_VAR = "dev"
PROD_CONFIG_VAR = "prod"
TESTING_CONFIG_VAR = "testing"

# Database
DATABASE_URL_ENV_NAME = APP_NAME + "_DATABASE_URL"
DATABASE_URL = os.getenv(DATABASE_URL_ENV_NAME)

TESTING_DATABASE_URL_ENV_NAME = APP_NAME + "_TESTING_DATABASE_URL"
TESTING_DATABASE_URL = os.getenv(TESTING_DATABASE_URL_ENV_NAME)

# Roles
ROLES_YAML_ENV_VAR = APP_NAME + "_ROLES"
OWNER_ROLE_NAME = "owner"
ADMIN_ROLE_NAME = "admin"
CASHIER_ROLE_NAME = "cashier"


